### ISSUE TITLE
java.lang.NoClassDefFoundError: com.zsoft.signala_longpolling.transport.longpolling.NegotiatingState$1

### ISSUE THREAD

**Issue by meNESS** [erizet/SignalA#64]
Hi,

I want to recompile your project, but I'm getting following error after building the SignalA and the LongPolling libraries and import them as `.aar` to my project.

```
10-25 14:28:38.572    6366-6366/com.x.xE/AndroidRuntime﹕ FATAL EXCEPTION: main
    Process: com.x.x, PID: 6366
    java.lang.NoClassDefFoundError: com.zsoft.signala_longpolling.transport.longpolling.NegotiatingState$1
            at com.zsoft.signala_longpolling.transport.longpolling.NegotiatingState.OnRun(NegotiatingState.java:48)
            at com.zsoft.signala_longpolling.transport.longpolling.StopableStateWithCallback.Run(StopableStateWithCallback.java:29)
            at com.zsoft.signala.ConnectionBase.SetNewState(ConnectionBase.java:54)
            at com.zsoft.signala_longpolling.transport.longpolling.DisconnectedState.OnRun(DisconnectedState.java:42)
            at com.zsoft.signala.transport.StateBase.Run(StateBase.java:28)
            at com.zsoft.signala_longpolling.transport.longpolling.DisconnectedState.Start(DisconnectedState.java:25)
            at com.zsoft.signala.ConnectionBase.Start(ConnectionBase.java:155)
            at com.x.x.services.RealtimeService.initConnection(RealtimeService.java:318)
            at com.x.x.services.RealtimeService.onCreate(RealtimeService.java:209)
            at android.app.ActivityThread.handleCreateService(ActivityThread.java:2761)
            at android.app.ActivityThread.access$1800(ActivityThread.java:151)
            at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1386)
            at android.os.Handler.dispatchMessage(Handler.java:102)
            at android.os.Looper.loop(Looper.java:135)
            at android.app.ActivityThread.main(ActivityThread.java:5254)
            at java.lang.reflect.Method.invoke(Native Method)
            at java.lang.reflect.Method.invoke(Method.java:372)
            at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:903)
            at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:698)
```

**Comment by hbthegreat** [comment]
Did you ever solve this @meNESS? I am having the same issue.

**Comment by meNESS** [comment]
@hbthegreat SignalA is deprecated. You have to use [this one.](https://github.com/SignalR/java-client). SignalA has lots of problems without any support. I made a huge application with SignalR without any problem.

**Comment by hbthegreat** [comment]
Thank you for your response @meNESS I might have to switch over to using that other library instead. I did however get SignalA functioning correctly for myself in an application yesterday so it does still work just missing some maven/gradle steps to get running correctly.

**Comment by meNESS** [comment]
@hbthegreat SignalA has some huge problems (e.g. not correctly handling threads and pool which would make an exception if you make lots of alive connections). I recommend you forget SignalA and use SignalR insread today. Otherwise, you have to migrate to that library very soon, I believe in that.

**Comment by Ashyrmyrat** [comment]
Hello
